spring.application.name=Bud-Cal
server.port=8080
server.address=0.0.0.0
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://<username>:<password>@<cluster-url>/budcal?retryWrites=true&w=majority}
spring.data.mongodb.database=${MONGODB_DATABASE:budcal}
spring.thymeleaf.cache=false
