spring.application.name=Bud-Cal
server.port=8080
server.address=0.0.0.0
spring.data.mongodb.uri=mongodb://budcal-mongo:27017/budcal
spring.data.mongodb.database=budcal
spring.thymeleaf.cache=false
server.servlet.session.tracking-modes=cookie
